version: "2"
services:

   db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "challenge"
      MYSQL_USER: "demo"
      MYSQL_PASSWORD: "demo"

   app:
    build: ./App
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "/bin/bash", "wait_until_db_ready.sh" ]
    

